### ISSUE TITLE
missing brace before line 52 in Display-Object.ps1

### ISSUE THREAD

**Issue by quog** [Phil-Factor/PowerShell-Utility-Cmdlets#1]
Hi Phil, 
there seems to be a missing brace before line 52 in Display-Object.ps1, and an additional brace at line 55.
https://github.com/Phil-Factor/PowerShell-Utility-Cmdlets/blob/ceec81afb9d910d3169ce8b19e0e9d5f959ff3ef/Display-Object/Display-Object.ps1#L52
https://github.com/Phil-Factor/PowerShell-Utility-Cmdlets/blob/ceec81afb9d910d3169ce8b19e0e9d5f959ff3ef/Display-Object/Display-Object.ps1#L55

**Comment by Phil-Factor** [comment]
oops. Thanks for spotting this, and letting me know. Hopefully now working.

**Comment by Phil-Factor** [comment]
seems to work now \with my tests
