### ISSUE TITLE
Elseif is inside if

### ISSUE THREAD

**Issue by swannsonite** [Phil-Factor/PowerShell-Utility-Cmdlets#2]
https://github.com/Phil-Factor/PowerShell-Utility-Cmdlets/blob/ceec81afb9d910d3169ce8b19e0e9d5f959ff3ef/Display-Object/Display-Object.ps1#L52

elseif : The term 'elseif' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
+     elseif ($ObjectTypeName -eq 'Collection`1')#and anything else it  ...
+     ~~~~~~
    + CategoryInfo          : ObjectNotFound: (elseif:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
$TheOldObject=$TheObject
        $TheObject=$TheOldObject|ForEach-Object{[pscustomobject]$_}

**Comment by Phil-Factor** [comment]
how embarassing Thanks for spotting this, and letting me know. Hopefully it is now working.

**Comment by Phil-Factor** [comment]
Closed hopefully with new fix
